### ISSUE TITLE
Fix wording 01-lesson-getting_familiar.md

### ISSUE THREAD

**Issue by mistergareth** [davekrh/ocp310_for_operations#3]
Rephrase last statement in 01-lesson-getting_familiar.md.

Change "Please ensure ansible is working properly and that your OpenShift virtual machines are reachable before proceeding."

to "Review your results to ensure it matches the sample output above, confirming that ansible is working properly and your OpenShift virtual machines are reachable before proceeding."

**Comment by mistergareth** [comment]
New pull request with the fix. 33a3ed7

**Comment by mistergareth** [comment]
Added to Patch-4 pull request for easy merge.

**Comment by davekrh** [comment]
Merged patch 5aade96. Thanks!
