### ISSUE TITLE
RPM package list 03-lesson-install_initial_software.md

### ISSUE THREAD

**Issue by mistergareth** [davekrh/ocp310_for_operations#5]
Can I suggest that we add the following couple packages to the list of RPMs that are installed.
They are two that I make a habit of checking for and installing immediately on any new system.

vim-enhanced
screen

- vim-enhanced give you the nice extra niceties that vim offers on Linux. Screen may be handy for the advanced or power users as they walk through the labs. Also, vim-enhanced will pull in vim package.

- Or maybe add it as a second, optional set of packages to install if you want to avoid confusion with what's *actually* an OCP dependency.

For example:

```
[student@workstation ~]$ sudo ansible -f 3 all -m shell -a 'yum install -y \
  wget git net-tools \
  bind-utils yum-utils \
  iptables-services bridge-utils \
  bash-completion kexec-tools \
  sos psacct openshift-ansible \
  docker vim-enhanced screen'
```

**Comment by mistergareth** [comment]
See patches and pull requests. If ok, you can just merge.

**Comment by mistergareth** [comment]
Added to Patch 4 for easy merge.

**Comment by davekrh** [comment]
Approved. screen is a best practice.
